# Generated by Django 4.0.2 on 2022-02-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('treatment_indications', models.CharField(max_length=300)),
                ('contraindications', models.CharField(max_length=300)),
                ('package_type', models.CharField(choices=[('Glass', 'Glass'), ('PlasticBox', 'PlasticBox'), ('Pills', 'Pills')], max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=300)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('person_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('symptom', models.CharField(max_length=300)),
                ('duration', models.IntegerField(verbose_name='Duration in days')),
                ('consequences', models.CharField(max_length=300)),
                ('drug1_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smth1', to='clinic.drug')),
                ('drug2_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smth2', to='clinic.drug')),
                ('drug3_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smth3', to='clinic.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('compensation', models.FloatField()),
                ('duties', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('appointment_date', models.DateTimeField()),
                ('employee_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.employee')),
                ('illness_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.illness')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.position'),
        ),
    ]
